Bookstore: styling
fredo509/Bookstore pull request #5
Opened 2023-05-12 19:31 UTC by fredo509

For this milestone I : 

-Update the design

2023-05-12 20:56 UTC, cynthiainga requested changes
Hi @fredo509, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)

## Highlights

- [ ] No linters errors ✔️ 
- [ ] Correct Gitflow ✔️ 

## Required Changes ♻️

- [ ] Please check the comments under the review 👇🏾 👇🏾 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-12 20:56 UTC, cynthiainga commented on src/App.css
- [ ] As mentioned the design is supposed to be exactly the same as the one provided on [Zeplin](https://zeplin.io/), take a look at your design and the given design below 👇🏾 👇🏾 

Your design

<img width="960" alt="Screenshot 2023-05-12 at 23 13 11" src="https://github.com/fredo509/Bookstore/assets/74501523/e9feec6b-ebc8-436a-979d-0cee8f3ee3a7">

Original design

<img width="700" alt="Screenshot 2023-05-12 at 23 13 35" src="https://github.com/fredo509/Bookstore/assets/74501523/ec150545-4daa-4575-be85-ef63a0ce4455">

2023-05-13 00:01 UTC, AmaduKamara requested changes
# Status: Required Changes ♻️ ♻️ ♻️

Hi @fredo509,

Good job working on the changes highlighted by the previous reviewer 👍🏽

There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

✅ You used Gitflow correctly 👍🏽
✅ The Linter checks passed successfully 👍🏽
✅ The app runs fine as expected 👍🏽

## Required Changes ♻️
_Check the comments under the review._

- [ ] Kindly align the horizontal line and the input fields and button of the form element to the right end just as it's in the original design so your design looks neat and organized 👍🏽

**Your Design**
<img width="1718" alt="Screenshot 2023-05-12 at 11 53 55 PM" src="https://github.com/fredo509/Bookstore/assets/50941074/93f4b14c-e761-44f7-a4d0-92e634fb5211">

**The Original Design**
<img width="1045" alt="Screenshot 2023-05-12 at 11 52 03 PM" src="https://github.com/fredo509/Bookstore/assets/50941074/3c7493a4-ac3d-4cfe-aec2-f8b2033dc801">

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-05-13 12:04 UTC, sumairq approved these changes
### Hi @fredo509 , 

<img src="https://media4.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✔️ Good commit history
✔️Linters are passing
✔️Very professional README
✔️Correct Git flow
✔️Descriptive PR
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-13 12:24 UTC, merged